* Setup and Installation Notes

** General
*** To be able to run the command =add-apt-repository=
#+BEGIN_SRC shell
sudo apt install software-properties-common
#+END_SRC
*** Add a PPA (in Ubuntu)
#+BEGIN_EXAMPLE
sudo add-apt-repository ppa:<ppa_name>
#+END_EXAMPLE
** Byobu (terminal management)
*** DigitalOcean tutorial - [[https://www.digitalocean.com/community/tutorials/how-to-install-and-use-byobu-for-terminal-management-on-ubuntu-16-04][How To Install and Use Byobu for Terminal Management on Ubuntu 16.04]]
    - =CTRL+SHIFT+F2= will create a new session.
    - =ALT+UP= and =ALT+DOWN= will scroll through your sessions.
    - =F6= will detach your current Byobu session.
    - =SHIFT+F6= will detach (but not close) Byobu, and will maintain your SSH connection to the server. You can get back to Byobu with the byobu command.
    - =ALT+F6= will detach all connections to Byobu except for the current one.
    - =F2= creates new windows within the current session.
    - =F3= and =F4= scroll left and right through the windows list.
    - =CTRL+SHIFT+F3=/=F4= moves a window left and right through the windows list.
    - =F8= renames the current open window in the list.
    - =F7= lets you view scrollback history in the current window.

** HAProxy setup
*** Add the repository =vbernat/haproxy-1.8=
#+BEGIN_SRC shell
sudo add-apt-repository ppa:vbernat/haproxy-1.8
#+END_SRC
*** Install haproxy
#+BEGIN_SRC shell
sudo apt install haproxy
#+END_SRC

** SSL certificates
Ref: [[http://nategood.com/client-side-certificate-authentication-in-ngi][Client-side certificate auth in Nginx]]

#+BEGIN_SRC shell
# Create the CA Key and Certificate for signing Client Certs
openssl genrsa -des3 -out ca.key 4096
openssl req -new -x509 -days 365 -key ca.key -out ca.crt

# Create the Server Key, CSR, and Certificate
openssl genrsa -des3 -out server.key 1024
openssl req -new -key server.key -out server.csr

# We're self signing our own server cert here.  This is a no-no in production.
openssl x509 -req -days 365 -in server.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out server.crt

# Create the Client Key and CSR
openssl genrsa -des3 -out client.key 1024
openssl req -new -key client.key -out client.csr

# Sign the client certificate with our CA cert.  Unlike signing our own server cert, this is what we want to do.
openssl x509 -req -days 365 -in client.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out client.crt
#+END_SRC

** [[file:docker.org][Docker setup]]
** [[file:scrapyd.org][Scrapy setup]]
